apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argus-agent.fullname" . }}-config
  labels:
    {{- include "argus-agent.labels" . | nindent 4 }}
data:
  DASHBOARD_URL: {{ .Values.dashboard.url | quote }}
  CLUSTER_NAME: {{ .Values.dashboard.clusterName | quote }}
  DASHBOARD_TLS_ENABLED: {{ .Values.dashboard.tlsEnabled | quote }}
