apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argus-agent.fullname" . }}-secret
  labels:
    {{- include "argus-agent.labels" . | nindent 4 }}
type: Opaque
data:
  DASHBOARD_TOKEN: {{ .Values.dashboard.token | b64enc | quote }}
