{{- if gt (int .Values.backend.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "argus.fullname" . }}-backend
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "argus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}
---
{{- if gt (int .Values.frontend.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "argus.fullname" . }}-frontend
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "argus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
