{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argus.fullname" . }}-postgres
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: tcp-postgres
      protocol: TCP
      name: tcp-postgres
  selector:
    {{- include "argus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
